import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function formatDate(dateStr: string | null): string {
  if (!dateStr) return "";
  const date = new Date(dateStr);
  const now = new Date();
  const diff = now.getTime() - date.getTime();
  const minutes = Math.floor(diff / 60000);
  const hours = Math.floor(diff / 3600000);
  const days = Math.floor(diff / 86400000);

  if (minutes < 1) return t("刚刚");
  if (minutes < 60) return `${minutes} ${t("分钟前")}`;
  if (hours < 24) return `${hours} ${t("小时前")}`;
  if (days < 7) return `${days} ${t("天前")}`;

  return date.toLocaleDateString("zh-CN", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });
}

export function truncate(str: string, len: number): string {
  if (str.length <= len) return str;
  return str.slice(0, len) + "...";
}

export let currentLang = "zh";

export const translations: Record<string, Record<string, string>> = {
  zh: {
    "设置": "设置",
    "AI 服务": "AI 服务",
    "Agent 参数": "Agent 参数",
    "Token 用量": "Token 用量",
    "外观": "外观",
    "同步": "同步",
    "标签": "标签",
    "批量标签": "批量标签",
    "关于": "关于",
    "标签库": "标签库",
    "重复检测": "重复检测",
    "未使用": "未使用",
    "新建标签": "新建标签",
    "没有找到标签": "没有找到标签",
    "搜索标签...": "搜索标签...",
    "添加": "添加",
    "标签已添加": "标签已添加",
    "添加失败": "添加失败",
    "标签已更新": "标签已更新",
    "更新失败": "更新失败",
    "标签已删除": "标签已删除",
    "删除失败": "删除失败",
    "别名已添加": "别名已添加",
    "别名已删除": "别名已删除",
    "标签已合并": "标签已合并",
    "合并失败": "合并失败",
    "合并标签": "合并标签",
    "将此标签的所有文章移动到另一个标签，然后删除此标签": "将此标签的所有文章移动到另一个标签，然后删除此标签",
    "选择目标标签": "选择目标标签",
    "合并到选中标签": "合并到选中标签",
    "没有检测到重复标签": "没有检测到重复标签",
    "复数变体": "复数变体",
    "命名变体": "命名变体",
    "拼写变体": "拼写变体",
    "合并到": "合并到",
    "删除未使用标签": "删除未使用标签",
    "个标签已删除": "个标签已删除",
    "全部": "全部",
    "临时": "临时",
    "有别名": "有别名",
    "潜在重复": "潜在重复",
    "过滤": "过滤",
    "输入标签（逗号分隔）": "输入标签（逗号分隔）",
    "Suggested": "建议",
    "Generating suggestions...": "生成建议中...",
    "Did you mean:": "你是不是想说：",
    "Existing": "已有",
    "已应用": "已应用",
    "No tags yet": "暂无标签",
    "配置": "配置",
    "范围选择": "范围选择",
    "1周": "1周",
    "1月": "1月",
    "3月": "3月",
    "半年": "半年",
    "1年": "1年",
    "未读": "未读",
    "跳过已批量打标签的文章": "跳过已批量打标签的文章",
    "跳过已有标签的文章": "跳过已有标签的文章",
    "并发度": "并发度",
    "候选文章数": "候选文章数",
    "估算中": "估算中",
    "超过 100 篇": "超过 100 篇",
    "超过 2000 篇安全上限": "超过 2000 篇安全上限",
    "开始": "开始",
    "运行中": "运行中",
    "进度": "进度",
    "成功": "成功",
    "失败": "失败",
    "已处理": "已处理",
    "中止": "中止",
    "准备就绪": "准备就绪",
    "建议标签": "建议标签",
    "审查新标签提案": "审查新标签提案",
    "以下标签由 AI 提出，请确认是否保留": "以下标签由 AI 提出，请确认是否保留",
    "标签名": "标签名",
    "命中次数": "命中次数",
    "涉及文章数": "涉及文章数",
    "决定": "决定",
    "保留": "保留",
    "丢弃": "丢弃",
    "全部保留": "全部保留",
    "全部丢弃": "全部丢弃",
    "应用": "应用",
    "请完成所有标签的审查决定": "请完成所有标签的审查决定",
    "应用中": "应用中",
    "批量标签完成": "批量标签完成",
    "添加标签关联": "添加标签关联",
    "创建新标签": "创建新标签",
    "保留提案": "保留提案",
    "丢弃提案": "丢弃提案",
    "重新开始": "重新开始",
    "已取消": "已取消",
    "批量标签操作已取消": "批量标签操作已取消",
    "每日 Token 用量": "每日 Token 用量",
    "Tokens": "Tokens",
    "输入": "输入",
    "输出": "输出",
    "请求数": "请求数",
    "总计": "总计",
    "提示 token": "提示 token",
    "补全 token": "补全 token",
    "成功率": "成功率",
    "平均/请求": "平均/请求",
    "模型对比": "模型对比",
    "加载中": "加载中",
    "阅读": "阅读",
    "选择一篇文章开始阅读": "选择一篇文章开始阅读",
    "原文": "原文",
    "翻译": "翻译",
    "回到原文": "回到原文",
    "清除翻译": "清除翻译",
    "摘要": "摘要",
    "笔记": "笔记",
    "导出": "导出",
    "导出原文 (Markdown)": "导出原文 (Markdown)",
    "导出 AI 摘要 (Markdown)": "导出 AI 摘要 (Markdown)",
    "导出笔记 (Markdown)": "导出笔记 (Markdown)",
    "导出失败": "导出失败",
    "已导出": "已导出",
    "暂无摘要": "暂无摘要",
    "暂无笔记": "暂无笔记",
    "语言": "语言",
    "中文": "中文",
    "英文": "英文",
    "简体中文": "简体中文",
    "繁体中文": "繁体中文",
    "日文": "日文",
    "韩文": "韩文",
    "法文": "法文",
    "德文": "德文",
    "西班牙文": "西班牙文",
    "葡萄牙文-巴西": "葡萄牙文-巴西",
    "俄文": "俄文",
    "阿拉伯文": "阿拉伯文",
    "印地文": "印地文",
    "刚刚": "刚刚",
    "分钟前": "分钟前",
    "小时前": "小时前",
    "天前": "天前",
    "篇": "篇",
    "条": "条",
    "个": "个",
  },
  en: {
    "设置": "Settings",
    "AI 服务": "AI Services",
    "Agent 参数": "Agent Settings",
    "Token 用量": "Token Usage",
    "外观": "Appearance",
    "同步": "Sync",
    "标签": "Tags",
    "批量标签": "Batch Tagging",
    "关于": "About",
    "标签库": "Tag Library",
    "重复检测": "Duplicates",
    "未使用": "Unused",
    "新建标签": "New Tag",
    "没有找到标签": "No tags found",
    "搜索标签...": "Search tags...",
    "添加": "Add",
    "标签已添加": "Tag added",
    "添加失败": "Add failed",
    "标签已更新": "Tag updated",
    "更新失败": "Update failed",
    "标签已删除": "Tag deleted",
    "删除失败": "Delete failed",
    "别名已添加": "Alias added",
    "别名已删除": "Alias deleted",
    "标签已合并": "Tags merged",
    "合并失败": "Merge failed",
    "合并标签": "Merge Tags",
    "将此标签的所有文章移动到另一个标签，然后删除此标签": "Move all articles from this tag to another tag, then delete this tag",
    "选择目标标签": "Select target tag",
    "合并到选中标签": "Merge into selected tag",
    "没有检测到重复标签": "No duplicate tags detected",
    "复数变体": "Plural variant",
    "命名变体": "Naming variant",
    "拼写变体": "Spelling variant",
    "合并到": "Merge into",
    "删除未使用标签": "Delete unused tags",
    "个标签已删除": " tags deleted",
    "全部": "All",
    "临时": "Provisional",
    "有别名": "Has alias",
    "潜在重复": "Potential duplicate",
    "过滤": "Filter",
    "输入标签（逗号分隔）": "Enter tags (comma separated)",
    "Suggested": "Suggested",
    "Generating suggestions...": "Generating suggestions...",
    "Did you mean:": "Did you mean:",
    "Existing": "Existing",
    "已应用": "Applied",
    "No tags yet": "No tags yet",
    "配置": "Configure",
    "范围选择": "Range",
    "1周": "1 week",
    "1月": "1 month",
    "3月": "3 months",
    "半年": "6 months",
    "1年": "1 year",
    "未读": "Unread",
    "跳过已批量打标签的文章": "Skip already batch-tagged articles",
    "跳过已有标签的文章": "Skip articles with existing tags",
    "并发度": "Concurrency",
    "候选文章数": "Candidate articles",
    "估算中": "Estimating...",
    "超过 100 篇": "Over 100 articles",
    "超过 2000 篇安全上限": "Over 2000 articles (safety limit)",
    "开始": "Start",
    "运行中": "Running",
    "进度": "Progress",
    "成功": "Success",
    "失败": "Failed",
    "已处理": "Processed",
    "中止": "Stop",
    "准备就绪": "Ready",
    "建议标签": "Suggested tags",
    "审查新标签提案": "Review new tag proposals",
    "以下标签由 AI 提出，请确认是否保留": "The following tags were suggested by AI. Please confirm whether to keep them:",
    "标签名": "Tag name",
    "命中次数": "Hit count",
    "涉及文章数": "Article count",
    "决定": "Decision",
    "保留": "Keep",
    "丢弃": "Discard",
    "全部保留": "Keep all",
    "全部丢弃": "Discard all",
    "应用": "Apply",
    "请完成所有标签的审查决定": "Please complete all tag review decisions",
    "应用中": "Applying",
    "批量标签完成": "Batch tagging complete",
    "添加标签关联": "Tag associations added",
    "创建新标签": "New tags created",
    "保留提案": "Proposals kept",
    "丢弃提案": "Proposals discarded",
    "重新开始": "Restart",
    "已取消": "Cancelled",
    "批量标签操作已取消": "Batch tagging operation cancelled",
    "每日 Token 用量": "Daily Token Usage",
    "Tokens": "Tokens",
    "输入": "Input",
    "输出": "Output",
    "请求数": "Requests",
    "总计": "Total",
    "提示 token": "Prompt tokens",
    "补全 token": "Completion tokens",
    "成功率": "Success rate",
    "平均/请求": "Avg/request",
    "模型对比": "Model Comparison",
    "加载中": "Loading...",
    "阅读": "Reading",
    "选择一篇文章开始阅读": "Select an article to start reading",
    "原文": "Original",
    "翻译": "Translate",
    "回到原文": "Back to original",
    "清除翻译": "Clear translation",
    "摘要": "Summary",
    "笔记": "Notes",
    "导出": "Export",
    "导出原文 (Markdown)": "Export original (Markdown)",
    "导出 AI 摘要 (Markdown)": "Export AI summary (Markdown)",
    "导出笔记 (Markdown)": "Export notes (Markdown)",
    "导出失败": "Export failed",
    "已导出": "Exported",
    "暂无摘要": "No summary available",
    "暂无笔记": "No notes available",
    "语言": "Language",
    "中文": "Chinese",
    "英文": "English",
    "简体中文": "Simplified Chinese",
    "繁体中文": "Traditional Chinese",
    "日文": "Japanese",
    "韩文": "Korean",
    "法文": "French",
    "德文": "German",
    "西班牙文": "Spanish",
    "葡萄牙文-巴西": "Portuguese (Brazil)",
    "俄文": "Russian",
    "阿拉伯文": "Arabic",
    "印地文": "Hindi",
    "刚刚": "Just now",
    "分钟前": "minutes ago",
    "小时前": "hours ago",
    "天前": "days ago",
    "篇": "articles",
    "条": "entries",
    "个": "",
  },
};

export function setLang(lang: string) {
  currentLang = lang;
  localStorage.setItem("uiLang", lang);
}

export function t(key: string): string {
  return translations[currentLang]?.[key] || key;
}