import Foundation
import Testing
@testable import Mercury

@Suite("Digest Template Store")
@MainActor
struct DigestTemplateStoreTests {
    @Test("Load built-in digest template from app bundle")
    func loadBuiltInTemplateFromBundle() throws {
        let store = DigestTemplateStore()
        let bundle = try mercuryAppBundle()
        try store.loadBuiltInTemplates(bundle: bundle, subdirectory: DigestTemplateStore.builtInSubdirectory)

        #expect(store.loadedTemplateIDs.contains("single-text"))
        #expect(store.loadedTemplateIDs.contains("single-markdown"))
        #expect(store.loadedTemplateIDs.contains("multiple-markdown"))
    }

    @Test("Load single-text template and render conditional note")
    func loadAndRenderSingleTextTemplate() throws {
        let store = DigestTemplateStore()
        try store.loadTemplates(from: templateDirectoryInRepository())

        let template = try store.template(id: "single-text")
        #expect(template.version == "v1")
        #expect(template.requiredPlaceholders == ["articleTitle", "articleURL"])
        #expect(template.optionalPlaceholders.contains("articleAuthor"))
        #expect(template.defaultParameters.isEmpty)
        #expect(template.repeatedSectionNames.isEmpty)

        let renderedWithoutNote = try template.render(
            context: DigestTemplateRenderContext(
                scalars: [
                    "articleTitle": "Mercury",
                    "articleAuthor": "Neo",
                    "articleURL": "https://example.com/article"
                ]
            )
        )
        #expect(renderedWithoutNote == "Mercury by Neo https://example.com/article")

        let renderedWithNote = try template.render(
            context: DigestTemplateRenderContext(
                scalars: [
                    "articleTitle": "Mercury",
                    "articleURL": "https://example.com/article",
                    "includeNote": "true",
                    "noteText": "Worth reading."
                ]
            )
        )
        #expect(renderedWithNote == "Mercury https://example.com/article Worth reading.")
    }

    @Test("Load single-markdown template and render summary and note sections")
    func loadAndRenderSingleMarkdownTemplate() throws {
        let store = DigestTemplateStore()
        try store.loadTemplates(from: templateDirectoryInRepository())

        let template = try store.template(id: "single-markdown")
        #expect(template.version == "v1")
        #expect(template.requiredPlaceholders.contains("digestTitle"))
        #expect(template.optionalPlaceholders.contains("includeSummary"))
        #expect(template.optionalPlaceholders.contains("labelSource"))
        #expect(template.defaultParameters["labelNote"] == "My Take")
        #expect(template.repeatedSectionNames.isEmpty)

        let rendered = try template.render(
            context: DigestTemplateRenderContext(
                scalars: [
                    "exportDateTimeISO8601": "2026-03-29T12:00:00Z",
                    "digestTitle": "Digest Title",
                    "fileSlug": "digest-title",
                    "articleTitle": "Mercury",
                    "articleAuthor": "Neo",
                    "articleURL": "https://example.com/article",
                    "includeSummary": "true",
                    "summaryTextBlockquote": "Line 1\n> Line 2",
                    "summaryTargetLanguage": "en",
                    "summaryDetailLevel": "medium",
                    "includeNote": "true",
                    "noteText": "My note",
                    "labelSource": "Source",
                    "labelAuthor": "Author",
                    "labelNote": "My Take",
                    "generatedByLine": "Generated by [Mercury](https://github.com/neolee/mercury)"
                ]
            )
        )

        #expect(rendered.contains("title = 'Digest Title'"))
        #expect(rendered.contains("**Source**: [Mercury](https://example.com/article)<br>"))
        #expect(rendered.contains("> Line 1\n> Line 2"))
        #expect(rendered.contains("**My Take**: My note"))
        #expect(rendered.contains("Generated by [Mercury](https://github.com/neolee/mercury)"))
    }

    @Test("Load multiple-markdown template and render repeated entry sections")
    func loadAndRenderMultipleMarkdownTemplate() throws {
        let store = DigestTemplateStore()
        try store.loadTemplates(from: templateDirectoryInRepository())

        let template = try store.template(id: "multiple-markdown")
        #expect(template.version == "v1")
        #expect(template.requiredPlaceholders.contains("entries"))
        #expect(template.optionalPlaceholders.contains("articleTitle"))
        #expect(template.defaultParameters["labelSource"] == "Source")
        #expect(template.repeatedSectionNames == ["entries"])

        let rendered = try template.render(
            context: DigestTemplateRenderContext(
                scalars: [
                    "exportDateTimeISO8601": "2026-03-29T12:00:00Z",
                    "digestTitle": "Weekly Digest",
                    "fileSlug": "weekly-digest",
                    "generatedByLine": "Generated by [Mercury](https://github.com/neolee/mercury)"
                ],
                repeatedSections: [
                    "entries": [
                        DigestTemplateRenderContext(
                            scalars: [
                                "articleTitle": "Entry One",
                                "articleAuthor": "Neo",
                                "articleURL": "https://example.com/1",
                                "labelSource": "Source",
                                "labelAuthor": "Author",
                                "labelNote": "My Take",
                                "includeNote": "true",
                                "noteText": "Thought"
                            ]
                        ),
                        DigestTemplateRenderContext(
                            scalars: [
                                "articleTitle": "Entry Two",
                                "articleAuthor": "Neo",
                                "articleURL": "https://example.com/2",
                                "labelSource": "Source",
                                "labelAuthor": "Author",
                                "labelNote": "My Take"
                            ]
                        )
                    ]
                ]
            )
        )

        #expect(rendered.contains("## Entry One"))
        #expect(rendered.contains("## Entry Two"))
        #expect(rendered.contains("**My Take**: Thought"))
        #expect(rendered.components(separatedBy: "Generated by [Mercury](https://github.com/neolee/mercury)").count == 2)
    }

    @Test("Repeated sections must be provided when declared by template")
    func repeatedSectionsMustBeProvidedWhenDeclared() throws {
        let store = DigestTemplateStore()
        try store.loadTemplates(from: templateDirectoryInRepository())

        let template = try store.template(id: "multiple-markdown")

        do {
            _ = try template.render(
                context: DigestTemplateRenderContext(
                    scalars: [
                        "exportDateTimeISO8601": "2026-03-29T12:00:00Z",
                        "digestTitle": "Weekly Digest",
                        "fileSlug": "weekly-digest"
                    ]
                )
            )
            Issue.record("Expected missing repeated section validation failure, but rendering succeeded.")
        } catch let error as DigestTemplateError {
            guard case let .missingRepeatedSection(name) = error else {
                Issue.record("Unexpected error kind: \(error.localizedDescription)")
                return
            }
            #expect(name == "entries")
        }
    }

    @Test("Reject malformed digest template with missing required placeholder")
    func rejectMalformedDigestTemplate() throws {
        let directory = try makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let invalidTemplate = """
        id: digest.invalid
        version: v1
        requiredPlaceholders:
          - articleTitle
          - articleURL
        template: |
          {{articleTitle}}
        """
        let fileURL = directory.appendingPathComponent("digest.invalid.yaml")
        try invalidTemplate.write(to: fileURL, atomically: true, encoding: .utf8)

        let store = DigestTemplateStore()
        do {
            try store.loadTemplates(from: directory)
            Issue.record("Expected malformed digest template validation failure, but loading succeeded.")
        } catch let error as DigestTemplateError {
            guard case let .invalidTemplateFile(name, reason) = error else {
                Issue.record("Unexpected error kind: \(error.localizedDescription)")
                return
            }
            #expect(name == "digest.invalid.yaml")
            #expect(reason.contains("Required placeholder(s) not found"))
            #expect(reason.contains("articleURL"))
        }
    }

    @Test("Reject malformed digest template with repeated section name missing from body")
    func rejectMalformedDigestTemplateWithMissingRepeatedSectionBody() throws {
        let directory = try makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let invalidTemplate = """
        id: digest.invalid
        version: v1
        repeatedSectionNames:
          - entries
        requiredPlaceholders:
          - digestTitle
        template: |
          {{digestTitle}}
        """
        let fileURL = directory.appendingPathComponent("digest.invalid.yaml")
        try invalidTemplate.write(to: fileURL, atomically: true, encoding: .utf8)

        let store = DigestTemplateStore()
        do {
            try store.loadTemplates(from: directory)
            Issue.record("Expected malformed digest template validation failure, but loading succeeded.")
        } catch let error as DigestTemplateError {
            guard case let .invalidTemplateFile(name, reason) = error else {
                Issue.record("Unexpected error kind: \(error.localizedDescription)")
                return
            }
            #expect(name == "digest.invalid.yaml")
            #expect(reason.contains("Repeated section(s) not found"))
            #expect(reason.contains("entries"))
        }
    }

    @Test("Reject malformed digest template when repeated section is not also required")
    func rejectMalformedDigestTemplateWhenRepeatedSectionIsNotRequired() throws {
        let directory = try makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let invalidTemplate = """
        id: digest.invalid
        version: v1
        repeatedSectionNames:
          - entries
        requiredPlaceholders:
          - digestTitle
        optionalPlaceholders:
          - articleTitle
        template: |
          {{digestTitle}}

          {{#entries}}
          {{articleTitle}}
          {{/entries}}
        """
        let fileURL = directory.appendingPathComponent("digest.invalid.yaml")
        try invalidTemplate.write(to: fileURL, atomically: true, encoding: .utf8)

        let store = DigestTemplateStore()
        do {
            try store.loadTemplates(from: directory)
            Issue.record("Expected malformed digest template validation failure, but loading succeeded.")
        } catch let error as DigestTemplateError {
            guard case let .invalidTemplateFile(name, reason) = error else {
                Issue.record("Unexpected error kind: \(error.localizedDescription)")
                return
            }
            #expect(name == "digest.invalid.yaml")
            #expect(reason.contains("must also be declared in `requiredPlaceholders`"))
            #expect(reason.contains("entries"))
        }
    }

    private func templateDirectoryInRepository() throws -> URL {
        let testsDirectory = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
        let templateDirectory = testsDirectory
            .appendingPathComponent("../Mercury/Resources/Digest/Templates")
            .standardizedFileURL

        guard FileManager.default.fileExists(atPath: templateDirectory.path) else {
            throw TestError.templateDirectoryNotFound(templateDirectory.path)
        }
        return templateDirectory
    }

    private func makeTemporaryDirectory() throws -> URL {
        let url = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("mercury-digest-template-tests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func mercuryAppBundle() throws -> Bundle {
        if let bundle = Bundle.allBundles.first(where: { $0.bundleIdentifier == "net.paradigmx.Mercury" }) {
            return bundle
        }
        if let bundle = Bundle.allBundles.first(where: { $0.bundleURL.lastPathComponent == "Mercury.app" }) {
            return bundle
        }
        throw TestError.appBundleNotFound
    }
}

private enum TestError: Error {
    case templateDirectoryNotFound(String)
    case appBundleNotFound
}
